stages:
- name: push-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: pheurtley/orangeid:nginx-test
      pushRemote: true
      registry: ${docker-registry}
      envFrom:
        sourceName: pheurtley-hub
        sourceKey: .dockerconfigjson
        targetKey: docker-registry