stages:
- name: push-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${docker-registry}/pheurtley/orangeid:nginx-test
      pushRemote: true
      registry: ${docker-registry}
      envFrom:
        sourceName: docker-hub-ph
        sourceKey: .dockerconfigjson
        targetKey: docker-registry